--- #YAML:1.0
name:               RTG-Report
version:            1.15
abstract:           RTG Reporting and data processing
author:
    - Matt Simerson (matt@layeredtech.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::Std:   0.0.4
    Date::Calc:    5.4
    DBIx::Simple:  1.26
    MIME::Lite:    3
    Net::SMTP:     0.5
    Text::CSV:     0.5
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
